name: "Run lint, unit tests, and cover"

on:
  pull_request:
    branches:
      - main


jobs:

  run-lint:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install nox
      run: |
        python -m pip install nox

    - name: Run lint
      run: |
        nox -s lint

    - name: Run lint_setup
      run: |
        nox -s lint_setup

  run-unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        w_grcp_gcp: ["", "_grpc_gcp"]
        python:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install nox
      run: |
        python -m pip install nox

    - name: Run unit tests
      env:
        COVERAGE_FILE: .coverage${{ matrix.w_grcp_gcp }}-${{matrix.python }}
      run: |
        nox -s unit${{ matrix.w_grcp_gcp }}-${{ matrix.python }}

    - name: Upload coverage results
      uses: actions/upload-artifact@v2
      with:
        name: coverage-artifacts
        path: .coverage${{ matrix.w_grcp_gcp }}-${{ matrix.python }}

  report-coverage:
    runs-on: ubuntu-latest
    needs:
        - run-unittests

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Download coverage results
      uses: actions/download-artifact@v2
      with:
        name: coverage-artifacts
        path: .coverage-results/

    - name: Install coverage
      run: |
        python -m pip install nox

    - name: Report coverage results
      run: |
        coverage combine .coverage-results/
        coverage report --show-missing --fail-under=100
